### ISSUE TITLE
Can't rebind controls functionality work

### ISSUE THREAD

**Issue by pang-lan** [ExOK/Celeste64#75]
When I see #63,I'm realize out to express the importance of the "rebind controls" functionality for me, as I play Celeste using a non-QWERTY keyboard layout. 

When I exploring the source to understand how controls are configured, I stumbled upon the ControlsConfig.cs file, which seems to predefine the control keys for the game. Given my limited experience with C# (becase this is my first time diving into C# code), I attempted to modify the ControlsConfig to suit my needs. Unfortunately, my changes did not take effect as I had hoped.

How do I successfully make changes to ControlsConfig?

**Comment by NoelFB** [comment]
Hi, once you've played the game once it will save the controls to a `.json` file, called `controls.json` which will be in `AppData/Roaming/Celeste64` on Windows or `./local/share/Celeste64` otherwise. You can modify that file to customize the controls. Alternatively if you change the default ones in C# you will need to [comment out line 42 of Startup.cs](https://github.com/ExOK/Celeste64/blob/main/Source/Scenes/Startup.cs#L42) where it loads the config file.

**Comment by pang-lan** [comment]
thanks! it's useful

**Comment by Akeem29** [comment]
Hello! I'm playing on M2 Mac, but use the version for x86-64 Mac. I can't find the controls.json file
